09/26/2021, 10:20:10 || pyUltLogs [INFO] - 
                -----------------------------------
                        Starting Deployment
                -----------------------------------

09/26/2021, 10:20:10 || pyUltLogs [INFO] - py-Ultroid Version - 63.0-beta
09/26/2021, 10:20:10 || pyUltLogs [INFO] - Telethon Version - 1.23.0
09/26/2021, 10:20:10 || pyUltLogs [INFO] - Ultroid Version - 0.2
09/26/2021, 10:20:10 || pyUltLogs [INFO] - Connecting to redis database
09/26/2021, 10:20:10 || pyUltLogs [INFO] - Trying to login.
09/26/2021, 10:20:10 || Telethon.network.mtprotosender [WARNING] - Attempt 1 at connecting failed: ConnectionRefusedError: [Errno 111] Connect call failed ('149.154.175.54', 443)
09/26/2021, 10:20:11 || pyUltLogs [INFO] - Logged in as Devesh Pal
09/26/2021, 10:20:11 || pyUltLogs [INFO] - Trying to login.
09/26/2021, 10:20:14 || pyUltLogs [INFO] - Logged in as @KarbonCopyBot
